USE [master]
GO

/****** Object:  Database [SquareEnixTest]    Script Date: 06/10/2020 19:15:20 ******/
CREATE DATABASE [SquareEnixTest]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SquareEnixTest', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS06\MSSQL\DATA\SquareEnixTest.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SquareEnixTest_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS06\MSSQL\DATA\SquareEnixTest_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SquareEnixTest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SquareEnixTest] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SquareEnixTest] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SquareEnixTest] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SquareEnixTest] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SquareEnixTest] SET ARITHABORT OFF 
GO

ALTER DATABASE [SquareEnixTest] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SquareEnixTest] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SquareEnixTest] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SquareEnixTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SquareEnixTest] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SquareEnixTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SquareEnixTest] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SquareEnixTest] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SquareEnixTest] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SquareEnixTest] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SquareEnixTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SquareEnixTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SquareEnixTest] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SquareEnixTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SquareEnixTest] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SquareEnixTest] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SquareEnixTest] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SquareEnixTest] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SquareEnixTest] SET  MULTI_USER 
GO

ALTER DATABASE [SquareEnixTest] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SquareEnixTest] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SquareEnixTest] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SquareEnixTest] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SquareEnixTest] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SquareEnixTest] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SquareEnixTest] SET  READ_WRITE 
GO


